# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a packages directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS      += "qti-auto-kernel"
BBFILE_PATTERN_qti-auto-kernel   = "^${LAYERDIR}/"
BBFILE_PRIORITY_qti-auto-kernel  = "12"
LAYERSERIES_COMPAT_qti-auto-kernel = "kirkstone scarthgap"
